РК №2 Чернецов Семён ИУ5-65Б

Вариант №16



In [133]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn import preprocessing, linear_model
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import mean_squared_error
from math import sqrt
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import r2_score
%matplotlib inline
sns.set(style="ticks")
from sklearn import tree
from sklearn.svm import SVR, NuSVR, LinearSVR
from sklearn.preprocessing import LabelEncoder, StandardScaler

Подключаем датасет.

In [134]:
df=pd.read_csv(r'C:\Users\Admin\Downloads\restaurant-scores-lives-standard.csv')

Просмотр датасета

In [135]:
df

business_id          business_name          business_address  \
0           101192           Cochinita #2  2 Marina Blvd Fort Mason   
1            97975             BREADBELLY           1408 Clement St   
2            92982  Great Gold Restaurant             3161 24th St.   
3           101389                 HOMAGE         214 CALIFORNIA ST   
4            85986           Pronto Pizza               798 Eddy St   
...            ...                    ...                       ...   
53968        89569     Blue Bottle Coffee              2 South Park   
53969        99764              POKE KANA              65 CAMBON Dr   
53970        84541           Philz Coffee             300 Folsom St   
53971        91572      El Gran Taco Loco          4591 Mission St.   
53972        89569     Blue Bottle Coffee              2 South Park   

       business_city business_state business_postal_code  business_latitude  \
0      San Francisco             CA                  NaN                NaN   
1      San Francisco             CA                94118                NaN   
2      San Francisco             CA                94110                NaN   
3      San Francisco             CA                94111                NaN   
4      San Francisco             CA                94109                NaN   
...              ...            ...                  ...                ...   
53968  San Francisco             CA                94107                NaN   
53969  San Francisco             CA                94132                NaN   
53970  San Francisco             CA                94105                NaN   
53971  San Francisco             CA                94112                NaN   
53972  San Francisco             CA                94107                NaN   

       business_longitude business_location  business_phone_number  ...  \
0                     NaN               NaN           1.415043e+10  ...   
1                     NaN               NaN           1.415724e+10  ...   
2                     NaN               NaN                    NaN  ...   
3                     NaN               NaN           1.415488e+10  ...   
4                     NaN               NaN                    NaN  ...   
...                   ...               ...                    ...  ...   
53968                 NaN               NaN                    NaN  ...   
53969                 NaN               NaN                    NaN  ...   
53970                 NaN               NaN                    NaN  ...   
53971                 NaN               NaN                    NaN  ...   
53972                 NaN               NaN                    NaN  ...   

                inspection_type           violation_id  \
0                 New Ownership                    NaN   
1         Routine - Unscheduled  97975_20190725_103124   
2                 New Ownership                    NaN   
3              New Construction                    NaN   
4                 New Ownership  85986_20161011_103114   
...                         ...                    ...   
53968     Routine - Unscheduled  89569_20190506_103124   
53969  New Ownership - Followup                    NaN   
53970     Routine - Unscheduled  84541_20190506_103133   
53971     Routine - Unscheduled  91572_20190506_103116   
53972     Routine - Unscheduled  89569_20190506_103157   

                                   violation_description  risk_category  \
0                                                    NaN            NaN   
1      Inadequately cleaned or sanitized food contact...  Moderate Risk   
2                                                    NaN            NaN   
3                                                    NaN            NaN   
4                           High risk vermin infestation      High Risk   
...                                                  ...            ...   
53968  Inadequately cleaned or sanitized food contact...  Moderate Risk   
53969  

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53973 entries, 0 to 53972
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   business_id                53973 non-null  int64  
 1   business_name              53973 non-null  object 
 2   business_address           53973 non-null  object 
 3   business_city              53973 non-null  object 
 4   business_state             53973 non-null  object 
 5   business_postal_code       52955 non-null  object 
 6   business_latitude          34417 non-null  float64
 7   business_longitude         34417 non-null  float64
 8   business_location          34417 non-null  object 
 9   business_phone_number      17035 non-null  float64
 10  inspection_id              53973 non-null  object 
 11  inspection_date            53973 non-null  object 
 12  inspection_score           40363 non-null  float64
 13  inspection_type            53973 non-null  obj

Количество пропусков для каждого признака

In [137]:
df.isnull().sum()

business_id                      0
business_name                    0
business_address                 0
business_city                    0
business_state                   0
business_postal_code          1018
business_latitude            19556
business_longitude           19556
business_location            19556
business_phone_number        36938
inspection_id                    0
inspection_date                  0
inspection_score             13610
inspection_type                  0
violation_id                 12870
violation_description        12870
risk_category                12870
Neighborhoods (old)          19594
Police Districts             19594
Supervisor Districts         19594
Fire Prevention Districts    19646
Zip Codes                    19576
Analysis Neighborhoods       19594
dtype: int64

Заполним пропуски признака inspection_score значением медианы

In [138]:
df['inspection_score'].median()

87.0

In [139]:
df['inspection_score'].fillna(df['inspection_score'].median(), inplace=True)

In [140]:
df

business_id          business_name          business_address  \
0           101192           Cochinita #2  2 Marina Blvd Fort Mason   
1            97975             BREADBELLY           1408 Clement St   
2            92982  Great Gold Restaurant             3161 24th St.   
3           101389                 HOMAGE         214 CALIFORNIA ST   
4            85986           Pronto Pizza               798 Eddy St   
...            ...                    ...                       ...   
53968        89569     Blue Bottle Coffee              2 South Park   
53969        99764              POKE KANA              65 CAMBON Dr   
53970        84541           Philz Coffee             300 Folsom St   
53971        91572      El Gran Taco Loco          4591 Mission St.   
53972        89569     Blue Bottle Coffee              2 South Park   

       business_city business_state business_postal_code  business_latitude  \
0      San Francisco             CA                  NaN                NaN   
1      San Francisco             CA                94118                NaN   
2      San Francisco             CA                94110                NaN   
3      San Francisco             CA                94111                NaN   
4      San Francisco             CA                94109                NaN   
...              ...            ...                  ...                ...   
53968  San Francisco             CA                94107                NaN   
53969  San Francisco             CA                94132                NaN   
53970  San Francisco             CA                94105                NaN   
53971  San Francisco             CA                94112                NaN   
53972  San Francisco             CA                94107                NaN   

       business_longitude business_location  business_phone_number  ...  \
0                     NaN               NaN           1.415043e+10  ...   
1                     NaN               NaN           1.415724e+10  ...   
2                     NaN               NaN                    NaN  ...   
3                     NaN               NaN           1.415488e+10  ...   
4                     NaN               NaN                    NaN  ...   
...                   ...               ...                    ...  ...   
53968                 NaN               NaN                    NaN  ...   
53969                 NaN               NaN                    NaN  ...   
53970                 NaN               NaN                    NaN  ...   
53971                 NaN               NaN                    NaN  ...   
53972                 NaN               NaN                    NaN  ...   

                inspection_type           violation_id  \
0                 New Ownership                    NaN   
1         Routine - Unscheduled  97975_20190725_103124   
2                 New Ownership                    NaN   
3              New Construction                    NaN   
4                 New Ownership  85986_20161011_103114   
...                         ...                    ...   
53968     Routine - Unscheduled  89569_20190506_103124   
53969  New Ownership - Followup                    NaN   
53970     Routine - Unscheduled  84541_20190506_103133   
53971     Routine - Unscheduled  91572_20190506_103116   
53972     Routine - Unscheduled  89569_20190506_103157   

                                   violation_description  risk_category  \
0                                                    NaN            NaN   
1      Inadequately cleaned or sanitized food contact...  Moderate Risk   
2                                                    NaN            NaN   
3                                                    NaN            NaN   
4                           High risk vermin infestation      High Risk   
...                                                  ...            ...   
53968  Inadequately cleaned or sanitized food contact...  Moderate Risk   
53969  

Удалим признаки класса object

In [141]:
df.drop(['business_name'], axis=1, inplace=True)
df.drop(['business_postal_code'],axis=1, inplace=True)
df.drop(['inspection_type'],axis=1, inplace=True)
df.drop(['violation_id'],axis=1, inplace=True)
df.drop(['violation_description'],axis=1, inplace=True)
df.drop(['inspection_date'],axis=1, inplace=True)
df.drop(['risk_category'],axis=1, inplace=True)
df.drop(['business_address'],axis=1, inplace=True)
df.drop(['business_city'],axis=1, inplace=True)
df.drop(['business_state'],axis=1, inplace=True)
df.drop(['business_location'],axis=1, inplace=True)
df.drop(['inspection_id'],axis=1, inplace=True)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53973 entries, 0 to 53972
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   business_id                53973 non-null  int64  
 1   business_latitude          34417 non-null  float64
 2   business_longitude         34417 non-null  float64
 3   business_phone_number      17035 non-null  float64
 4   inspection_score           53973 non-null  float64
 5   Neighborhoods (old)        34379 non-null  float64
 6   Police Districts           34379 non-null  float64
 7   Supervisor Districts       34379 non-null  float64
 8   Fire Prevention Districts  34327 non-null  float64
 9   Zip Codes                  34397 non-null  float64
 10  Analysis Neighborhoods     34379 non-null  float64
dtypes: float64(10), int64(1)
memory usage: 4.5 MB


Удалим строки с пропусками и разобьём датасет на обучающую и тестовую выборки

In [143]:
df= df.dropna()

In [144]:
X = df.drop('inspection_score', axis=1).values
y = df['inspection_score'].values
X, y

(array([[ 4.79400000e+03,  3.77786340e+01, -1.22393089e+02, ...,
          6.00000000e+00,  2.88560000e+04,  3.40000000e+01],
        [ 6.36190000e+04,  3.77761330e+01, -1.22419484e+02, ...,
          7.00000000e+00,  2.88520000e+04,  3.60000000e+01],
        [ 3.64900000e+03,  3.77657080e+01, -1.22409002e+02, ...,
          8.00000000e+00,  2.88530000e+04,  2.00000000e+01],
        ...,
        [ 5.83700000e+03,  3.77672310e+01, -1.22436377e+02, ...,
          1.50000000e+01,  2.88620000e+04,  5.00000000e+00],
        [ 7.64300000e+03,  3.77121480e+01, -1.22452076e+02, ...,
          9.00000000e+00,  2.88610000e+04,  2.80000000e+01],
        [ 6.50570000e+04,  3.77972380e+01, -1.22434533e+02, ...,
          1.30000000e+01,  5.70000000e+01,  1.30000000e+01]]),
 array([ 71.,  87.,  87., ..., 100.,  87.,  80.]))

In [145]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

#### Градиентный бустинг

In [146]:
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
grad_boost = GradientBoostingRegressor()
grad_boost.fit(X_train, y_train)
ygrad_boost= grad_boost.predict(X_test)
y_train_grad_boost = grad_boost.predict(X_train)

print(
    y_train, ygrad_boost,
    y_test, y_train_grad_boost
)

[87. 94. 72. ... 92. 92. 87.] [86.96939393 83.92128243 87.12618389 ... 88.83414519 84.72884002
 82.59767857] [100.  87.  76. ...  90.  87.  83.] [87.51698524 89.48219088 85.36745509 ... 84.23378466 87.41039731
 86.05378034]


#### Метод опорных векторов:

In [147]:
SVRM =SVR(kernel='linear').fit(X_train, y_train)
ySVR= SVRM.predict(X_test)
y_train_SVR = SVRM.predict(X_train)

print(
    y_train, ySVR,
    y_test, y_train_SVR
)

[87. 94. 72. ... 92. 92. 87.] [2.12343279e+14 2.08794581e+14 2.50481571e+14 ... 8.68751033e+14
 1.97808928e+14 2.26704156e+14] [100.  87.  76. ...  90.  87.  83.] [1.72956732e+14 2.42076962e+14 2.34564982e+14 ... 1.72934996e+14
 1.83897912e+14 2.17489893e+14]
